# This workflow will run on push to main/master, run tests, and build the Docker image
name: Build Docker Image on Merge

on:
  push:
    branches: [ main, master ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          if [ -d "tests" ]; then pytest tests; else echo "No tests directory found."; fi

      - name: Build Docker image
        run: |
          docker build -t notification_service .
